import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';
import { Carousel } from 'react-responsive-carousel';
import { HomeContainer, PortfolioContainer } from '../../../assets/styles/HomeStyles';
import Animate from '../../../components/Animation/Animate';
import Contact from '../../../components/Contact';
import Footer from '../../../components/Layout/Footer';
import Header from '../../../components/Layout/Header';
import Layout from '../../../components/Layout/Layout';
import { ContainerCenter } from '../../../components/Layout/styles';
import Social from '../../../components/Social';
import { IconArrowLeft, IconArrowRight, IconGlobal } from '../../../components/Svg';
import apiTropa from '../../api/api';
import Home from '../../index';

// import { Container } from './styles';

const PageHome: React.FC = () => {

    const router = useRouter()
    const { slug }: any = router.query
    const [data, setData] = useState<any>({})

    useEffect(() => {

        apiTropa.get('instagram').then(response => {
            setData({...response.data.result.data.filter((obj:any) => obj.id === slug)[0]})
        }).catch(err => {

        })

    }, [])

    return (
        <Layout>
            <HomeContainer>
                <Head>
                    <title>Tropa.Digital - Infinitas possibilidades</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon1.ico" />
                </Head>
                <Header
                    backgroundImage={data.media_url}
                    menus={[
                        {
                            href: '/home/o-que-fazemos',
                            value: 'O que fazemos',
                        },
                        {
                            href: '/home/a-tropa',
                            value: 'A Tropa',
                        },
                        {
                            href: '/home/social',
                            value: 'Social',
                        },
                        {
                            href: '/home/portfolio',
                            value: 'Portfolio',
                        },
                        {
                            href: '/home/contato',
                            value: 'contato',
                        },
                    ]}
                >
                    <h1>{data.media_url}</h1>
                </Header>

                <Social itemsToShow={3} />

                <Contact />
                <Footer />
            </HomeContainer>
        </Layout>
    )
};

export default PageHome;
