import { useRouter } from 'next/router';
import type { NextPage } from 'next';
import { LandingPage, LandingPageTwo, Mobile, PortfolioBanner, PortfolioContainer } from '../../assets/styles/PortfolioStyles';
import Head from 'next/head';
import Header from '../../components/Layout/Header';
import Animate from '../../components/Animation/Animate';
import { IconAstronaut, IconCube, IconFlag } from '../Svg';
import PulseLoader from "react-spinners/PulseLoader";

interface IPort {
    portfolioSelected: object | any ;
}

const Portfolio: NextPage<IPort> = ({
    portfolioSelected,
}) => {
    const router = useRouter();

    return (
        <PortfolioContainer>
            <Head>
                    <title>Tropa.Digital - Infinitas possibilidades</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon1.ico" />
            </Head>
            <Header
                backgroundImage={'/images/PortfolioBackground.png'}
                className="bannerSystemAnimation"
                menus={[
                    {
                        href: '/home/o-que-fazemos',
                        value: 'O que fazemos',
                    },
                    {
                        href: '/home/a-tropa',
                        value: 'A Tropa',
                    },
                    {
                        href: '/home/social',
                        value: 'Social',
                    },
                    {
                        href: '/home/portfolio',
                        value: 'Portfolio',
                    },
                    {
                        href: '/home/contato',
                        value: 'contato',
                    },
                ]}
            >
                <PortfolioBanner>
                    <div className="main">
                        <Animate effect="fadeInLeft" className="title">
                            <h1>
                                {portfolioSelected.titulo} 
                            </h1>
                        </Animate>                                             
                    </div>                         
                </PortfolioBanner>
            </Header>

            <LandingPage>
                <div className='title'>
                    <h1>Landing Page</h1>
                    <IconFlag />
                </div>

                <div className='page'>
                    {
                        portfolioSelected.imagem_principal !== undefined
                        ?
                        <img src={portfolioSelected.imagem_principal} alt="Imagem principal do site" />                    
                        :
                        <PulseLoader 
                            color="#fff"
                            size={30} 
                        />
                    }
                </div>

                <div className='text'>
                    <p>
                        {
                            portfolioSelected.landing  
                            ? portfolioSelected.landing.texto
                            : 
                            <PulseLoader 
                                color="#fff"
                                size={20} 
                            /> 
                        }
                    </p>
                    <p> 
                        Veja nosso trabalho acessando -&gt; &nbsp; 
                        <a href={portfolioSelected.link} target='_blank' rel="noreferrer">
                            {portfolioSelected.titulo}
                        </a> 
                    </p>
                </div>
            </LandingPage>   

            {
                portfolioSelected.mobile &&
                portfolioSelected.mobile.imagens !== undefined
                ?
                    <Mobile>                   
                        <div className='mobile-cube'>
                            <h1>Mobile</h1>
                            <p>Versão responsiva desenvolvida para celulares.</p>
                            <IconCube className="effect-stroke primary"/>
                        </div>

                            <div className='phones'>
                                <div className='phone'>                        
                                    <div className='cel'>
                                        <img src="/images/MobileBlack.png" alt="Celular com imagem do site" />                                
                                    </div>
                                    {
                                        portfolioSelected.mobile
                                        ?
                                        <div 
                                            className='back'
                                            style={{backgroundImage: `url(${portfolioSelected.mobile.imagens[0]})`}}
                                        />   
                                        :
                                        <div className='backLoader'>
                                            <PulseLoader 
                                                color="#fff"
                                                size={30} 
                                            />
                                        </div>     
                                    }                                                  
                                </div>
                                        
                                <div className='phone2'>                        
                                    <div className='cel2'>
                                        <img src="/images/MobileBlack.png" alt="Celular com imagem do site" />
                                    </div>
                                    {
                                        portfolioSelected.mobile
                                        ?
                                        <div 
                                            className='back2'     
                                            style={{backgroundImage: `url(${portfolioSelected.mobile.imagens[1]})`}}
                                        />        
                                        :
                                        <div className='backLoader2'>
                                            <PulseLoader 
                                                color="#fff"
                                                size={30} 
                                            />
                                        </div>     
                                    }                      
                                </div>
                            
                                <div className='phone3'>                        
                                    <div className='cel3'>
                                        <img src="/images/MobileBlack.png" alt="Celular com imagem do site" />
                                    </div>
                                    {
                                        portfolioSelected.mobile
                                        ?
                                        <div 
                                            className='back3'     
                                            style={{backgroundImage: `url(${portfolioSelected.mobile.imagens[2]})`}}
                                        />                          
                                        :
                                        <div className='backLoader3'>
                                            <PulseLoader 
                                                color="#fff"
                                                size={30} 
                                            />
                                        </div>     
                                    }
                                </div> 
                            </div>     

                        <div className='mobile-astro'>
                            <h1>mob</h1>
                            <IconAstronaut className="effect-stroke light"/>
                        </div> 
                        
                        <div className='paper'>
                            <button onClick={() => router.push('/home/contato')}>
                                <p>Tire seu projeto do</p>
                                <img src="/images/Paper.png" alt="Palavra papel circulada" />
                            </button>
                        </div>    

                    </Mobile>
                :
                <LandingPageTwo>
                    <div className='page-two'>
                    {
                        portfolioSelected.landing &&
                        portfolioSelected.landing.imagem2 !== ""
                        ?
                            <img src={portfolioSelected.landing.imagem2} alt="Segunda imagem do website" />                    
                        :
                            <PulseLoader 
                                color="#fff"
                                size={30} 
                            />
                    }
                    </div>
                    
                    <div className='paper'>
                        <button onClick={() => router.push('/home/contato')}>
                            <p>Tire seu projeto do</p>
                            <img src="/images/Paper.png" alt="Palavra papel circulada" />
                        </button>
                    </div> 
                    
                </LandingPageTwo>
            }
                
           
            
        </PortfolioContainer>
    )
}

export default Portfolio;