import { useRouter } from 'next/router';
import type { NextPage } from 'next';
import Layout from '../components/Layout/Layout';
import Head from 'next/head';
import Header from '../components/Layout/Header';
import Animate from '../components/Animation/Animate';
import WhyTropa from '../components/WhyTropa/WhyTropa';
import Contact from '../components/Contact';
import Footer from '../components/Layout/Footer';
import { BannerSystem, LanguagesContainer, SystemContainer } from '../assets/styles/SystemStyles';
import { ContainerCenter } from '../components/Layout/styles';
import WhatWeDo from '../components/WeDo';
import { IconCash, IconChatbot, IconDisk, IconGlobal, IconMessage } from '../components/Svg';

const Sistemas: NextPage = () => {
    const router = useRouter();
    return (
        <Layout>
            <SystemContainer>

                <Head>
                    <title>Tropa.Digital - Infinitas possibilidades</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon1.ico" />
                </Head>
                <Header
                    backgroundImage={'/images/SystemBackground.png'}
                    className="bannerSystemAnimation"
                    menus={[
                        {
                            href: '/home/o-que-fazemos',
                            value: 'O que fazemos',
                        },
                        {
                            href: '/home/a-tropa',
                            value: 'A Tropa',
                        },
                        {
                            href: '/home/social',
                            value: 'Social',
                        },
                        {
                            href: '/home/portfolio',
                            value: 'Portfolio',
                        },
                        {
                            href: '/home/contato',
                            value: 'contato',
                        },
                    ]}
                >
                    <BannerSystem>
                        <div className="main">
                            <Animate effect="fadeInLeft" className="title">
                                <h1>
                                    Sistemas                                   
                                </h1>
                                <h1 className="primary">
                                    Web                                   
                                </h1>
                            </Animate>                            
                            <button>Conheça</button>                            
                            <Animate effect="fadeInUp" className="note">
                                <img src="/images/Notebook1.png" />
                            </Animate>
                        </div>                         
                    </BannerSystem>
                </Header>

                <WhatWeDo
                    title="O Que Fazemos?"
                    description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent pellentesque suscipit nulla non vehicula."
                    icon={<IconGlobal className="effect-stroke grey" />}
                    items={[
                        {
                            icon:<IconChatbot />,
                            title: 'chatbot',
                            description:
                                'SIMULE AGORA MESMO.',
                        },
                        {   
                            icon:<IconCash />,
                            title: 'checkout transparente',
                            description:
                                'SIMULE AGORA MESMO.',
                        },
                        {   
                            icon:<IconMessage />,
                            title: 'Mensagerias',
                            description:
                                'SIMULE AGORA MESMO.',
                        },                        
                    ]}
                />

               
                

                <LanguagesContainer>
                    <ContainerCenter className="center">
                        <Animate effect="zoomIn">
                            <img src="/images/languages/node.png" />
                        </Animate>
                        <Animate effect="zoomIn">
                            <img src="/images/languages/reactjs.png" />
                        </Animate>
                        <Animate effect="zoomIn">
                            <img src="/images/languages/reactnative.png" />
                        </Animate>
                        <Animate effect="zoomIn">
                            <img src="/images/languages/scss.png" />
                        </Animate>
                        <Animate effect="zoomIn">
                            <img src="/images/languages/mysql.png" />
                        </Animate>
                        <Animate effect="zoomIn">
                            <img src="/images/languages/sqlserver.png" />
                        </Animate>
                    </ContainerCenter>
                </LanguagesContainer>

                <WhyTropa />
                
                <Contact />
                
                <Footer />
            </SystemContainer>
        </Layout>
    )
};

export default Sistemas;
