import { useRouter } from 'next/router';
import Head from 'next/head';
import type { NextPage } from 'next';
import StageItems from '../components/Stages';
import Header from '../components/Layout/Header';
import { IconCube } from '../components/Svg';
import { LanguagesContainer } from '../assets/styles/HomeStyles';
import { ContainerCenter } from '../components/Layout/styles';
import Animate from '../components/Animation/Animate';
import WhyTropa from '../components/WhyTropa/WhyTropa';
import WebSection from '../components/WebSection';
import Contact from '../components/Contact';
import Footer from '../components/Layout/Footer';
import { AppContainer, BannerApp } from '../assets/styles/AppStyles';
import Layout from '../components/Layout/Layout';

const Sites: NextPage = () => {
    
    const router = useRouter();

    return (
        <Layout>
            <AppContainer>
                <Head>
                    <title>Tropa.Digital - Infinitas possibilidades</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon1.ico" />
                </Head>
                <Header
                    className="bannerAppAnimation site"
                    menus={[
                        {
                            href: '/home/o-que-fazemos',
                            value: 'O que fazemos',
                        },
                        {
                            href: '/home/a-tropa',
                            value: 'A Tropa',
                        },
                        {
                            href: '/home/social',
                            value: 'Social',
                        },
                        {
                            href: '/home/portfolio',
                            value: 'Portfolio',
                        },
                        {
                            href: '/home/contato',
                            value: 'contato',
                        },
                    ]}
                >
                    <BannerApp className="site-variant">
                        <div className="main">
                            <Animate effect="fadeInLeft" className="title">
                                <h1>
                                    Website                                   
                                </h1>
                            </Animate>
                            <div className="title-transparent">
                                <h1 className="transparent">
                                    Website                                   
                                </h1>
                            </div>
                            <Animate effect="fadeInUp" className="mac">
                                <img src="/images/Mac.png" />
                            </Animate>                            
                        </div>                         
                    </BannerApp>
                </Header>
                
                <StageItems
                    title="Todas etapas"
                    description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent pellentesque suscipit nulla non vehicula."
                    icon={<IconCube className="effect-stroke grey" />}
                    items={[
                        {
                            title: 'Velocidade',
                            description:
                                'Lorem ipsum dolor sit amat, consectur apsdifja. Present pallange sucipt nulla nan vehicula.',
                        },
                        {
                            title: 'Facilidade',
                            description:
                                'Lorem ipsum dolor sit amat, consectur apsdifja. Present pallange sucipt nulla nan vehicula.',
                        },
                        {
                            title: 'Atendimento',
                            description:
                                'Lorem ipsum dolor sit amat, consectur apsdifja. Present pallange sucipt nulla nan vehicula.',
                        },
                        {
                            title: 'Design',
                            description:
                                'Lorem ipsum dolor sit amat, consectur apsdifja. Present pallange sucipt nulla nan vehicula.',
                        },
                    ]}
                />
                
                
                <LanguagesContainer>
                    <ContainerCenter className="center">
                        <Animate effect="zoomIn">
                            <img src="/images/languages/node.png" />
                        </Animate>
                        <Animate effect="zoomIn">
                            <img src="/images/languages/reactjs.png" />
                        </Animate>
                        <Animate effect="zoomIn">
                            <img src="/images/languages/reactnative.png" />
                        </Animate>
                        <Animate effect="zoomIn">
                            <img src="/images/languages/scss.png" />
                        </Animate>
                        <Animate effect="zoomIn">
                            <img src="/images/languages/mysql.png" />
                        </Animate>
                        <Animate effect="zoomIn">
                            <img src="/images/languages/sqlserver.png" />
                        </Animate>
                    </ContainerCenter>
                </LanguagesContainer>

                <WhyTropa />

                <WebSection />

                <Contact />
                
                <Footer />

            </AppContainer>
        </Layout>
    )
};

export default Sites;
